== Introduction

Why is there anything at all instead of nothing?
This is the fundamental question of metaphysics and the starting point of the system of thee c-ov-n.
It is this question that leads us in these explorations, from one question to another spiraling around this central question of being and nothingness.

What does it mean to be?
We find ourselves in a constantly changing world, how do we define ourselves?
Why are some aspects of our being accompanied by perception and consciousness?
As beings, what can we do?
What is meant by Will? "free" will?

The system of thee c-ov-n does not attempt to answer these questions so much as it provides a way to orient onself to the question.
Thee c-ov-n is a system of Magick, itself a method of exploration of the being and possibility.

=== Defining Magick

Magick is the weaving of the fabric of reality.
Magick is not merely a technique of working within natural law, it is a means of working beyond these laws.
Magick transcends the natural.
Magick is the art of the supernatural.footnote:[We choose to use the spelling "magick" in the tradition of Aliester Crowley to differentiate from works of illusion.]

With this definition we stake out in a bold direction.
We assert that magick is not mere metaphor for psychological processes.
Magick is not working by merely unknown mechanism.
Magick is not religion, nor is it a science.

There are many systems of magick, many paradigms.
What makes any worthy of being called "magick" is the ability to manifest results beyond natural means.
A comptent magickian must have some knowledge and skill of natural technologies, of the mind, body, physics, etc.
There is no reason to use magick for that which can be achieved directly, and natural techniques are almost always more reliable.
Magick, however, should be set apart.
Magick is miraculous.
So at the outset we find ourselves immediately to the fundamental paradox of magick:
How can magick be possible if at the core magick is the aims to manifest by impossible means?

One common response to this paradox is to declare that this definition of magick is an absurd self-contradiction and worth no further consideration or effort.
For those that believe the world to be entirely a complex mechasm of cause and effect this is the end of the matter.
If magick has no mechanism then it can not _do_ anything.

Many use the word "magick" differently, they side-step the paradox declaring that magick is entirely natural.
Indeed, many sciences were originally couched in mystery and mysticism, as Author C. Clarke wrote, "Any sufficiently advanced technology is indistinguishable from magic."
When apparently miraculous things occur as the result of some magick work it has obeyed some natural law simply not fully expressed or yet understood.
This is fine, as far as it goes, but it does not go anywhere in particular.
We aim to root this "magick" in a deeper place.
If we suspect that a action has effect by an unknown natural means then we should seek to express that means and pursue it by scientific study, but magick is result without mechanism and does not yield its secrets to scientific study.

Many do just fine practicing of magick without any fundamental theory and without opinions on the possiblity and imposibility.
Magick is a practice.
We _do_ magick.
So is how we _think_ about magick irrelevant?
I have found quite the opposite to be true.
Thinking is a kind of doing.
Just as when we meditate we may focus on clearing thoughts from our mind, when we are planning and executing ritual work how we think about the work shapes how results manifest.

This current work is the result of an obsession in exploring the paradox of magick.
The fundamental theory we put forth in this work is that magick only seems to be a paradox when we misunderstand reality and possibility.
Existence itself is a paradox and it is this paradox which permits magick.
Magick is the art that weaves the fabric of reality.
Magick happens outside of, beyond, reality.
Magick never has been something that is real or unreal, possible or impossible, because magick is not any of these things.
Magick is no-thing.

We will endevor to trace the thread of magick from non-being to manifest reality and beyond, to show how no-thing, non-being, makes everything manifest, carrying its incompleteness with it at every step.
In each step we will show how this can inform the practice of magick.

=== What is ANQ?

This book introduces the concepts and practices of working with the ANQ meta-magick system.
This is an open system with a structure inspired by Qabalah/Kabbalah, but with no intent to be an interpretation of such systems.

ANQ stands for ANQ's Not Qabalah, a nod to the https://gnu.org/[GNU project], "GNU's Not Unix".
The GNU project emerged in response to the ownership claims to the popular Unix operating system.
Like GNU, ANQ aims to create a free and open structure that can be built upon and manipulated in whatever manner the user desires.
ANQ is a meta-magick system that, like an operating system, aims to give you what you need to get your own customized magick environment up and running faster with a minimum of constraints placed on what you create on top of it.

The core of the ANQ system is the emergence of the Process Tree.
The first seeds of this work were planted in 1998.
When studying the Qabalah and the Tarot as presented by Aleister Crowley, the mind rejected it.
There was seen a brilliance obscured by too many obscurities, overburdened with syncretic associations.
It was clear that the best way forward to study the Qabalah was to not study the Qabalah, but rather water this minimal brilliant seed and see how it developed of its own accord.

Any true student of this work must likewise work with this system and come to their own understanding of it.
There are brilliant flashes of insight throughout its structure.
The only way to pluck this fruit is to make it your own.
Hesitate not at all to reject or reform any aspect or correspondence.
My own experience has taught me that there are many alternate forms of this emergent structure, each of which may be of use and have its own hidden treasure.
What is presented here is what has been found in my own exploration to be the most useful configuration.

The word “Qabalah” is used due to the obvious debt this system owes to other systems of Qabalah, particularly the Hermetic Qabalah and Aleister Crowley’s work in particular.
However, this system and its emergent method mark a deliberate break with traditional Qabalah.
We have no regard for whether the system presented here either elucidates the meaning of any other system of Qabalah or contradicts it.
The lack of correspondences such as the Hebrew alphabet and astrological associations are deliberate.
Practitioners are invited to add these, or other correspondences into the system or not as they find useful.

This work is licensed under the https://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution-ShareAlike 4.0 International License].

ifdef::env-github,backend-html5[]
link:01-Beginning.adoc[> Next - A Beginning >]
endif::[]
